USE [master]
GO
/****** Object:  Database [BDecommerce]    Script Date: 30/07/2020 10:59:55 ******/
CREATE DATABASE [BDecommerce]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDecommerce', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BDecommerce.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BDecommerce_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BDecommerce_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [BDecommerce] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDecommerce].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BDecommerce] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [BDecommerce] SET ANSI_NULLS ON 
GO
ALTER DATABASE [BDecommerce] SET ANSI_PADDING ON 
GO
ALTER DATABASE [BDecommerce] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [BDecommerce] SET ARITHABORT ON 
GO
ALTER DATABASE [BDecommerce] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BDecommerce] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BDecommerce] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BDecommerce] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BDecommerce] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [BDecommerce] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [BDecommerce] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BDecommerce] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [BDecommerce] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BDecommerce] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BDecommerce] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BDecommerce] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BDecommerce] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BDecommerce] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BDecommerce] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BDecommerce] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BDecommerce] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BDecommerce] SET RECOVERY FULL 
GO
ALTER DATABASE [BDecommerce] SET  MULTI_USER 
GO
ALTER DATABASE [BDecommerce] SET PAGE_VERIFY NONE  
GO
ALTER DATABASE [BDecommerce] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BDecommerce] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BDecommerce] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [BDecommerce] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'BDecommerce', N'ON'
GO
ALTER DATABASE [BDecommerce] SET QUERY_STORE = OFF
GO
USE [BDecommerce]
GO
/****** Object:  Table [dbo].[CLIENTE]    Script Date: 30/07/2020 10:59:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTE](
	[COD_CLIENTE] [int] NOT NULL,
	[NOM_CLIENTE] [varchar](100) NOT NULL,
	[NUM_CPF_CNPJ] [numeric](15, 0) NOT NULL,
	[DSC_ENDERECO] [varchar](100) NOT NULL,
	[NUM_TELEFONE] [numeric](14, 0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[COD_CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FORMA_PAGAMENTO]    Script Date: 30/07/2020 10:59:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FORMA_PAGAMENTO](
	[COD_FORMA_PAGAMENTO] [int] NOT NULL,
	[DSC_FORMA_PAGAMENTO] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[COD_FORMA_PAGAMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FORNECEDOR]    Script Date: 30/07/2020 10:59:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FORNECEDOR](
	[COD_FORNECEDOR] [int] NOT NULL,
	[NOM_FORNECEDOR] [varchar](100) NOT NULL,
	[NUM_CNPJ] [numeric](15, 0) NOT NULL,
	[DSC_ENDERECO] [varchar](1000) NOT NULL,
	[NUM_TELEFONE] [numeric](14, 0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[COD_FORNECEDOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ITEM_PEDIDO]    Script Date: 30/07/2020 10:59:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEM_PEDIDO](
	[NUM_PEDIDO] [int] NOT NULL,
	[COD_ITEM_PEDIDO] [int] NOT NULL,
	[COD_SERVICO] [int] NOT NULL,
	[QTD_SERVICO] [numeric](2, 0) NOT NULL,
	[VLR_TOTAL_ITEM] [numeric](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[COD_ITEM_PEDIDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pedido]    Script Date: 30/07/2020 10:59:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pedido](
	[NUM_PEDIDO] [int] IDENTITY(1,1) NOT NULL,
	[COD_CLIENTE] [int] NOT NULL,
	[DAT_PEDIDO] [datetime] NOT NULL,
	[VLR_TOTAL_PEDIDO] [numeric](10, 2) NOT NULL,
	[COD_FORMA_PAGAMENTO] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NUM_PEDIDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SERVICO]    Script Date: 30/07/2020 10:59:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SERVICO](
	[COD_SERVICO] [int] NOT NULL,
	[COD_FORNECEDOR] [int] NOT NULL,
	[DSC_SERVICO] [varchar](500) NOT NULL,
	[TIP_SERVICO] [varchar](50) NOT NULL,
	[VLR_SERVICO] [numeric](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[COD_SERVICO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ITEM_PEDIDO]  WITH CHECK ADD  CONSTRAINT [FK_COD_SERVICO] FOREIGN KEY([COD_SERVICO])
REFERENCES [dbo].[SERVICO] ([COD_SERVICO])
GO
ALTER TABLE [dbo].[ITEM_PEDIDO] CHECK CONSTRAINT [FK_COD_SERVICO]
GO
ALTER TABLE [dbo].[ITEM_PEDIDO]  WITH CHECK ADD  CONSTRAINT [FK_NUM_PEDIDO] FOREIGN KEY([NUM_PEDIDO])
REFERENCES [dbo].[Pedido] ([NUM_PEDIDO])
GO
ALTER TABLE [dbo].[ITEM_PEDIDO] CHECK CONSTRAINT [FK_NUM_PEDIDO]
GO
ALTER TABLE [dbo].[Pedido]  WITH CHECK ADD  CONSTRAINT [FK_COD_CLIENTE] FOREIGN KEY([COD_CLIENTE])
REFERENCES [dbo].[CLIENTE] ([COD_CLIENTE])
GO
ALTER TABLE [dbo].[Pedido] CHECK CONSTRAINT [FK_COD_CLIENTE]
GO
ALTER TABLE [dbo].[Pedido]  WITH CHECK ADD  CONSTRAINT [FK_COD_FORMA_PAGAMENTO] FOREIGN KEY([COD_FORMA_PAGAMENTO])
REFERENCES [dbo].[FORMA_PAGAMENTO] ([COD_FORMA_PAGAMENTO])
GO
ALTER TABLE [dbo].[Pedido] CHECK CONSTRAINT [FK_COD_FORMA_PAGAMENTO]
GO
ALTER TABLE [dbo].[SERVICO]  WITH CHECK ADD  CONSTRAINT [FK_SERVICO_FORNECEDOR] FOREIGN KEY([COD_FORNECEDOR])
REFERENCES [dbo].[FORNECEDOR] ([COD_FORNECEDOR])
GO
ALTER TABLE [dbo].[SERVICO] CHECK CONSTRAINT [FK_SERVICO_FORNECEDOR]
GO
USE [master]
GO
ALTER DATABASE [BDecommerce] SET  READ_WRITE 
GO
