CREATE TABLE ALUNO
(	COD_ALUNO INT NOT NULL,
	NOM_ALUNO VARCHAR(100) NOT NULL
);

CREATE TABLE [dbo].[CURSO]
(
	[COD_CURSO] [INT] NOT NULL,
	[NOM_CURSO] [VARCHAR] (100) NOT NULL
)
GO

CREATE TABLE [dbo].[MATRICULA]
(	[COD_ALUNO] [INT] NOT NULL,
	[COD_CURSO] [INT] NOT NULL,
	[DAT_MATRICULA] [datetime] NOT NULL
) ON [PRIMARY]
GO

USE [BDTESTE]
GO

CREATE SYNONYM TB_ALUNO_NEW FOR ALUNO;

SELECT * FROM ALUNO;
SELECT * FROM TB_ALUNO_NEW;

--INFORMA TUDO SOBRE A TABELA, MUITO UTIL 
sp_help	'CURSO'
sp_help	'ALUNO'

FQN

SELECT * FROM BDTESTE.dbo.ALUNO;


ALTER TABLE ALUNO
ADD CONSTRAINT PK_ALUNO	PRIMARY KEY CLUSTERED
(
	COD_ALUNO
);


ALTER TABLE CURSO
ADD CONSTRAINT PK_CURSO	PRIMARY KEY CLUSTERED
(
	COD_CURSO
);

ALTER TABLE ALUNO ADD COD_CURSO_FK int NOT NULL;

--AUMENTAR TAMANHO DA COLUNA
ALTER TABLE CURSO ALTER COLUMN NOM_CURSO VARCHAR (200) NOT NULL;

--DIMINUIR TAMANHO DA COLUNA
ALTER TABLE CURSO ALTER COLUMN NOM_CURSO VARCHAR (50) NOT NULL;
ALTER TABLE CURSO ALTER COLUMN NOM_CURSO VARCHAR (12) NOT NULL; --ERROR (JÁ É POPULADA COM TAMANHO 12)

--CONFERIR DADOS DA COLUNA
SELECT * FROM CURSO

--INSERIR DADOS NA COLUNA
INSERT INTO CURSO VALUES (1,'LINGUAGEM SQL');
INSERT INTO CURSO VALUES (2,'T-SQL');

--TAMANHO DOS VALORES DA COLUNA (CONTAR CARACTER DE UMA LINHA)
SELECT COD_CURSO, LEN (NOM_CURSO) FROM CURSO;

--DIMINUIR TAMANHO COM TABELA POPULAR SEM VIOLAR O TAMANHO DOS DADOS EXISTENTES
ALTER TABLE CURSO ALTER COLUMN NOM_CURSO VARCHAR (13) NOT NULL;

--ADICIONAR CAMPO NOT NULL COM TABELA POPULADA
ALTER TABLE CURSO ADD VLR_CURSO MONEY NOT NULL; --ERROR
ALTER TABLE CURSO ADD VLR_CURSO MONEY NULL;
ALTER TABLE CURSO ADD NOTA MONEY NULL; --TESTE
UPDATE CURSO SET VLR_CURSO = 10000

sp_help	'CURSO'
sp_help	'ALUNO'

--OPCAO 2

ALTER TABLE CURSO ADD IND_STATUS CHAR (1) NOT NULL DEFAULT 'S';
SELECT * FROM CURSO;

--ADICIONAR CHAVE ESTRANGEIRA COD_CURSO_FK NA TABELA ALUNO
ALTER TABLE ALUNO
ADD CONSTRAINT  FK_ALUNO_CURSO FOREIGN KEY
(
	COD_CURSO_FK
) REFERENCES CURSO
(
	COD_CURSO
)
ON UPDATE NO ACTION
ON DELETE NO ACTION;

-- REMOVER, COLUMA  OU TABELA

--REMOVER SINONIMO 

DROP SYNONYM TB_ALUNO_NEW;

--REMOVE COLUNA
SELECT * FROM CURSO
ALTER TABLE CURSO DROP COLUMN NOM_ALUNO;

--REMOVE COLUNA (COM FK)

DROP TABLE ALUNO;
DROP TABLE CURSO;
DROP TABLE MATRICULA;

-- REMOVER BANCO DE DADOS

USE master;
DROP DATABASE BDTESTE;

sp_help	'CURSO'
 

SELECT *
FROM sysprocesses
WHERE blocked <> 0

SELECT *
FROM sys.dm_exec_requests
WHERE blocking_session_id <> 0