create database BDecommerce

use BDecommerce


create table dbo.CLIENTE (
							COD_CLIENTE INT NOT NULL,
							NOM_CLIENTE VARCHAR(1000) NOT NULL,
							NUM_CPF_CNPJ NUMERIC(15) NULL,
							DSC_ENDERECO_COBRANCA VARCHAR(1000) NOT NULL,
							NUM_TELEFONE NUMERIC(14) NOT NULL);
					  
					  
ALTER TABLE dbo.CLIENTE
  ADD CONSTRAINT PK_COD_CLIENTE PRIMARY KEY (COD_CLIENTE);
 					  
					  
					  
					  

create table dbo.FORMA_PAGAMENTO (
									COD_FORMA_PAGAMENTO INT NOT NULL,
									DSC_FORMA_PAGAMENTO VARCHAR(100) NOT NULL);
									
									
ALTER TABLE dbo.FORMA_PAGAMENTO
  ADD CONSTRAINT PK_COD_FORMA_PAGAMENTO PRIMARY KEY (COD_FORMA_PAGAMENTO);


  
  
  
create table dbo.PEDIDO (
							NUM_PEDIDO INT NOT NULL,
							COD_CLIENTE INT NOT NULL,
							DAT_PEDIDO DATETIME NOT NULL,
							VLR_TOTAL_PEDIDO NUMERIC(10,2) NULL,
							COD_FORMA_PAGAMENTO INT NOT NULL);
							


ALTER TABLE dbo.PEDIDO
  ADD CONSTRAINT PK_NUM_PEDIDO PRIMARY KEY (NUM_PEDIDO);
  
  
ALTER TABLE dbo.PEDIDO
ADD CONSTRAINT FK_COD_CLIENTE FOREIGN KEY (COD_CLIENTE)
REFERENCES dbo.CLIENTE (COD_CLIENTE);


ALTER TABLE dbo.PEDIDO
ADD CONSTRAINT FK_COD_FORMA_PAGAMENTO FOREIGN KEY (COD_FORMA_PAGAMENTO)
REFERENCES dbo.FORMA_PAGAMENTO (COD_FORMA_PAGAMENTO);




create table dbo.FORNECEDOR (
								COD_FORNECEDOR INT NOT NULL,
								NOM_FORNECEDOR VARCHAR(100) NOT NULL,
								NUM_CNPJ NUMERIC(15) NULL,
								DSC_ENDERECO VARCHAR(1000) NOT NULL,
								NUM_TELEFONE NUMERIC(14) NOT NULL);
								
								
ALTER TABLE dbo.FORNECEDOR
  ADD CONSTRAINT PK_COD_FORNECEDOR PRIMARY KEY (COD_FORNECEDOR);



create table dbo.SERVICO (
							COD_SERVICO INT NOT NULL,
							COD_FORNECEDOR INT NOT NULL,
							DSC_SERVICO VARCHAR(500) NOT NULL,
							TIP_SERVICO VARCHAR(50) NOT NULL,
							VLR_SERVICO NUMERIC(10,2) NOT NULL);
							

ALTER TABLE dbo.SERVICO
  ADD CONSTRAINT PK_COD_SERVICO PRIMARY KEY (COD_SERVICO);

ALTER TABLE dbo.SERVICO  
  ADD CONSTRAINT FK_COD_FORNECEDOR FOREIGN KEY (COD_FORNECEDOR)
  REFERENCES dbo.FORNECEDOR (COD_FORNECEDOR);
  
  
  
create table dbo.ITEM_PEDIDO (
								COD_ITEM_PEDIDO INT NOT NULL,
								NUM_PEDIDO INT NOT NULL,
								COD_SERVICO INT NOT NULL,
								QTD_SERVICO NUMERIC(2) NOT NULL,
								VLR_TOTAL_ITEM NUMERIC(10,2) NOT NULL);
								
								
ALTER TABLE dbo.ITEM_PEDIDO
  ADD CONSTRAINT PK_COD_ITEM_PEDIDO PRIMARY KEY (COD_ITEM_PEDIDO);

ALTER TABLE dbo.ITEM_PEDIDO  
  ADD CONSTRAINT FK_NUM_PEDIDO FOREIGN KEY (NUM_PEDIDO)
  REFERENCES dbo.PEDIDO (NUM_PEDIDO);								
								
ALTER TABLE dbo.ITEM_PEDIDO  
  ADD CONSTRAINT FK_COD_SERVICO FOREIGN KEY (COD_SERVICO)
  REFERENCES dbo.SERVICO (COD_SERVICO);						

























							